services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    restart: always 
    volumes:
      - ./pgdata:/var/lib/postgresql/data    
  service:
    #Make sure to change architecture to amd64 if you are running on x86_64
    image: "dafraer/effective-mobile-task:4.0-amd64"
    container_name: service
    depends_on:
      - postgres
    environment:
    #Change the environmental variables to your own
      PORT: ":8080"
      DB_URI: "postgres://postgres:mysecretpassword@postgres:5432/postgres?sslmode=disable"
    restart: always
    ports:
      - "8080:8080"